name: Release Docker image
on:
  push:
    tags: 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract Docker image metadata
        id: extract-docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: blolol/wheaties-brain-java
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: ${{ steps.extract-docker-metadata.outputs.labels }}
          push: true
          tags: ${{ steps.extract-docker-metadata.outputs.tags }}
