name: Release Docker image
on:
  push:
    tags: 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: zulu
      - name: Build and publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar docker dockerPush dockerPushLatest
          gradle-version: current
